import global from './global.png';
import detailJob from './detailJob.png';
import profil from './profil.png';
import directionDown from './direction-down.png';
import dropdown from './dropdown.png';
import icon from './icon.png';
import cargoGear from './cargoGearComp.png';
import var2 from './var2.png';
import dailyComp from './DailyExcessConsumtionComp.png';
import speedComp from './SpeedUnderperformanceComp.png';
import cargoLoadingComp from './CargoLoadingReportComp.png';
import cargoDischargeComp from './CargoDischargeReportComp.png';
import voyageComp from './VoyageExcessConsumptionComp.png';
import bunkerComp from './UpcomingBunkerDemandsComp.png';
import breakdownComp from './CraneBreakdownLossComp.png';
import grafik1 from './grafik1.png';
import statistik from './statistik.png';
import last from './last.png';

export { global, detailJob, profil, directionDown, dropdown, icon, cargoGear, var2, dailyComp, speedComp, cargoLoadingComp, cargoDischargeComp, voyageComp, bunkerComp, breakdownComp, grafik1, statistik, last };
